# Generated by Django 5.0.8 on 2024-09-03 05:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')])),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(max_length=9, unique=True)),
                ('first_year', models.CharField(max_length=4)),
                ('second_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')])),
                ('main_img_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('competition', models.ManyToManyField(blank=True, to='core.competition')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_k')),
            ],
        ),
    ]
