# Generated by Django 5.0.8 on 2024-09-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_K',
            new_name='TypeK',
        ),
    ]
