# Generated by Django 5.0.8 on 2026-03-06 23:57

from django.db import migrations, models


def add_core_columns_if_missing(apps, schema_editor):
    sqls = [
        "ALTER TABLE core_brand ADD COLUMN IF NOT EXISTS logo_dark_file varchar(100) NULL;",
        "ALTER TABLE core_brand ADD COLUMN IF NOT EXISTS logo_file varchar(100) NULL;",
        "ALTER TABLE core_club ADD COLUMN IF NOT EXISTS logo_dark_file varchar(100) NULL;",
        "ALTER TABLE core_club ADD COLUMN IF NOT EXISTS logo_file varchar(100) NULL;",
        "ALTER TABLE core_typek ADD COLUMN IF NOT EXISTS category varchar(20) NOT NULL DEFAULT 'match';",
        "ALTER TABLE core_typek ADD COLUMN IF NOT EXISTS is_goalkeeper boolean NOT NULL DEFAULT false;",
    ]
    for sql in sqls:
        schema_editor.execute(sql)
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS core_typek_categor_758349_idx ON core_typek (category, is_goalkeeper);"
    )


def reverse_add_core_columns(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='typek',
                    name='category',
                    field=models.CharField(
                        choices=[
                            ('match', 'Game'),
                            ('prematch', 'Pre-match'),
                            ('preseason', 'Pre-season'),
                            ('training', 'Training'),
                            ('travel', 'Travel'),
                        ],
                        db_index=True,
                        default='match',
                        help_text="Category for kit type classification. Note: 'jacket' items are handled as outerwear, not kits.",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name='typek',
                    name='is_goalkeeper',
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is a goalkeeper kit (GK, Goalkeeper, Portero)",
                    ),
                ),
                migrations.AddIndex(
                    model_name='typek',
                    index=models.Index(fields=['category', 'is_goalkeeper'], name='core_typek_categor_758349_idx'),
                ),
                migrations.AlterModelOptions(
                    name='typek',
                    options={'ordering': ['category', 'is_goalkeeper', 'name']},
                ),
                migrations.AddField(
                    model_name='brand',
                    name='logo_file',
                    field=models.ImageField(blank=True, null=True, upload_to='logos/brands/'),
                ),
                migrations.AddField(
                    model_name='brand',
                    name='logo_dark_file',
                    field=models.ImageField(blank=True, null=True, upload_to='logos/brands/'),
                ),
                migrations.AddField(
                    model_name='club',
                    name='logo_file',
                    field=models.ImageField(blank=True, null=True, upload_to='logos/clubs/'),
                ),
                migrations.AddField(
                    model_name='club',
                    name='logo_dark_file',
                    field=models.ImageField(blank=True, null=True, upload_to='logos/clubs/'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_core_columns_if_missing, reverse_add_core_columns),
            ],
        ),
    ]
