# Generated by Django 5.0.8 on 2025-09-15 06:30

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('outerwear', 'Outerwear'), ('tracksuit', 'Tracksuit'), ('pants', 'Pants'), ('other', 'Other')], help_text='Type of item', max_length=20)),
                ('name', models.CharField(help_text='Name or title of the item', max_length=200)),
                ('condition', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('design', models.CharField(blank=True, choices=[('PLAIN', 'Plain'), ('STRIPES', 'Stripes'), ('GRAPHIC', 'Graphic'), ('CHEST_BAND', 'Chest band'), ('CONTRASTING_SLEEVES', 'Contrasting sleeves'), ('PINSTRIPES', 'Pinstripes'), ('HOOPS', 'Hoops'), ('SINGLE_STRIPE', 'Single stripe'), ('HALF_AND_HALF', 'Half-and-half'), ('SASH', 'Sash'), ('CHEVRON', 'Chevron'), ('CHECKERS', 'Checkers'), ('GRADIENT', 'Gradient'), ('DIAGONAL', 'Diagonal'), ('CROSS', 'Cross'), ('QUARTERS', 'Quarters')], max_length=20)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='The country associated with this item', max_length=2, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competitions', models.ManyToManyField(blank=True, help_text='Competitions associated with this item', related_name='%(app_label)s_%(class)s_items', to='core.competition')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_value', models.CharField(default='#FF0000', help_text='Hexadecimal color value (e.g., #RRGGBB).', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('image_avif', models.ImageField(blank=True, null=True, upload_to='item_photos_avif/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jersey', serialize=False, to='collection.baseitem')),
                ('is_fan_version', models.BooleanField(default=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('has_nameset', models.BooleanField(default=False)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_short_sleeve', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otheritem', serialize=False, to='collection.baseitem')),
                ('type', models.CharField(choices=[('pin', 'Pin'), ('hat', 'Hat'), ('cap', 'Cap'), ('socks', 'Socks'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Outerwear',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outerwear', serialize=False, to='collection.baseitem')),
                ('type', models.CharField(choices=[('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('windbreaker', 'Windbreaker'), ('crewneck', 'Crewneck')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pants', serialize=False, to='collection.baseitem')),
            ],
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shorts', serialize=False, to='collection.baseitem')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_fan_version', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracksuit',
            fields=[
                ('base_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracksuit', serialize=False, to='collection.baseitem')),
            ],
        ),
    ]
