# Generated by Django 5.0.8 on 2024-09-04 01:45

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('shorts', 'Shorts'), ('jacket', 'Jacket')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('type', models.CharField(choices=[('pin', 'Pin'), ('hat', 'Hat'), ('cap', 'Cap'), ('socks', 'Socks'), ('other', 'Other')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('image_avif', models.ImageField(blank=True, null=True, upload_to='item_photos_avif/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_fan_version', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outerwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('type', models.CharField(choices=[('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('windbreaker', 'Windbreaker'), ('crewneck', 'Crewneck')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('is_fan_version', models.BooleanField(default=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('has_nameset', models.BooleanField(default=False)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_short_sleeve', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kit')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracksuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detailed_condition', models.CharField(choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_replica', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_color', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VARIOUS', 'Various'), ('KHAKI', 'Khaki'), ('TURQUOISE', 'Turquoise'), ('CREAM', 'Cream'), ('APRICOT', 'Apricot'), ('CORAL', 'Coral'), ('BURGUNDY', 'Burgundy'), ('ROSE', 'Rose'), ('LILAC', 'Lilac'), ('LIGHT_BLUE', 'Light Blue'), ('NAVY', 'Navy'), ('DARK_GREEN', 'Dark Green'), ('MUSTARD', 'Mustard'), ('MINT', 'Mint')], max_length=20), blank=True, null=True, size=3)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.size')),
                ('tags', models.ManyToManyField(blank=True, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
