# Generated by Django 5.0.8 on 2024-09-04 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pants',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pants',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tracksuit',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tracksuit',
            name='detailed_condition',
            field=models.CharField(blank=True, choices=[('BNWT', 'Brand New With Tags'), ('BNWOT', 'Brand New Without Tags'), ('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20),
        ),
    ]
