# Generated by Django 5.0.8 on 2026-03-06 23:57

import django.core.validators
from django.db import connection, migrations, models


def add_is_processing_photos_if_missing(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'collection_baseitem'
            AND column_name = 'is_processing_photos'
            """
        )
        if cursor.fetchone():
            return
    schema_editor.execute(
        "ALTER TABLE collection_baseitem ADD COLUMN is_processing_photos BOOLEAN NOT NULL DEFAULT FALSE;"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS collection_baseitem_is_processing_photos_idx "
        "ON collection_baseitem (is_processing_photos);"
    )


def reverse_add_is_processing_photos(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'collection_baseitem'
            AND column_name = 'is_processing_photos'
            """
        )
        if not cursor.fetchone():
            return
    schema_editor.execute("DROP INDEX IF EXISTS collection_baseitem_is_processing_photos_idx;")
    schema_editor.execute("ALTER TABLE collection_baseitem DROP COLUMN IF EXISTS is_processing_photos;")


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_add_baseitem_id_fka_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pants',
            options={'verbose_name_plural': 'Pants'},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='baseitem',
                    name='is_processing_photos',
                    field=models.BooleanField(db_index=True, default=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_is_processing_photos_if_missing, reverse_add_is_processing_photos),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_value',
            field=models.CharField(default='#FF0000', help_text='Hexadecimal color value (e.g., #RGB or #RRGGBB).', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{3}([0-9A-Fa-f]{3})?$', code='invalid_hex_color', message='Enter a valid hex color (#RGB or #RRGGBB).')]),
        ),
    ]
