# Generated by Django 5.0.8 on 2026-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_pants_options_baseitem_is_processing_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='fit',
            field=models.CharField(blank=True, choices=[('', '—'), ('too_small', 'Too small'), ('too_big', 'Too big'), ('just_right', 'Just right'), ('perfect', 'Perfect fit'), ('oversized_perfect', 'Oversized, perfect'), ('oversized_ok', 'Slightly oversized but fine')], db_index=True, help_text='Private note for filtering your collection by fit.', max_length=20, verbose_name='How it fits (private)'),
        ),
    ]
